# Generated by Django 5.1.5 on 2025-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('Welcome_Screen', 'Welcome_Screen'), ('About_Us', 'About_Us'), ('Feedback', 'Feedback')], db_column='banner_type', default='not_available', max_length=255)),
                ('banner_title', models.CharField(db_column='banner_title', default='not_available', max_length=555)),
                ('title_text', models.TextField(db_column='title_text', max_length=1025)),
                ('feedback_by', models.CharField(db_column='feedback_by', default='not_available', max_length=255)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(db_column='added_by', default='GP', max_length=255)),
            ],
            options={
                'db_table': 'ViewManager',
                'db_table_comment': 'View and manage the site contents',
            },
        ),
    ]
