# Generated by Django 5.1.5 on 2025-02-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorizedAccess_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_log', models.TextField(db_column='track_log', max_length=9999)),
                ('ip_logged', models.TextField(db_column='title_text', max_length=1025)),
                ('tracked_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UnauthorizedAccess_Tracker',
                'db_table_comment': 'Track and View Unauthorized Access',
            },
        ),
    ]
