# Generated by Django 5.1.5 on 2025-02-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0002_unauthorizedaccess_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthorizedaccess_tracker',
            name='ip_logged',
            field=models.TextField(db_column='title_text', max_length=1025, null=True),
        ),
        migrations.AlterField(
            model_name='unauthorizedaccess_tracker',
            name='track_log',
            field=models.TextField(db_column='track_log', max_length=9999, null=True),
        ),
    ]
