# Generated by Django 5.1.5 on 2025-02-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0003_alter_unauthorizedaccess_tracker_ip_logged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
                ('product_description', models.TextField(db_column='title_text', default='Not Defined', max_length=1025)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(db_column='added_by', default='GP', max_length=255)),
            ],
            options={
                'db_table': 'Products_List',
                'db_table_comment': 'Manage Product List',
            },
        ),
    ]
