# Generated by Django 5.1.5 on 2025-02-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0004_products_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_list',
            name='product_description',
            field=models.TextField(db_column='product_description', default='Not Defined', max_length=1025),
        ),
    ]
