# Generated by Django 5.1.5 on 2025-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0005_alter_products_list_product_description'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='products_list',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='unauthorizedaccess_tracker',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='viewmanager',
            table_comment=None,
        ),
        migrations.AlterField(
            model_name='products_list',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
