# Generated by Django 5.1.5 on 2025-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0008_products_list_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmanager',
            name='client_company',
            field=models.CharField(db_column='client_company', default='Anonymous', max_length=255),
        ),
    ]
