# Generated by Django 5.1.5 on 2025-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0009_viewmanager_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmanager',
            name='updated_by',
            field=models.CharField(db_column='updated_by', default='NA', max_length=255),
        ),
    ]
